configuration:
  ingress:
    external: true
    targetPort: 8080
    transport: Auto
template:
  scale:
    minReplicas: 1
    maxReplicas: 1
  containers:
    - image: ghcr.io/anrub/azdemo:2
      name: test
      probes:
        - type: Liveness
          httpGet:
            path: /out
            port: 8080
        - type: Readiness
          httpGet:
            path: /out
            port: 8080
        - type: Startup
          periodSeconds: 30
          failureThreshold: 10
          httpGet:
            path: /out
            port: 8080

      resources:
        memory: 1.5Gi
        cpu: 0.75
